#!/usr/bin/env ruby -I.
# The Awesome language!
#
# usage:
#   ./awesome example.awm # to eval a file
#   ./awesome             # to start the REPL
#
# on Windows run with: ruby -I. awesome [options]

require File.expand_path("../interpreter", __FILE__)
require "readline"

interpreter = Interpreter.new

# If a file is given we eval it.
if file = ARGV.first
  interpreter.eval File.read(file)

# Start the REPL. read-eval-print-loop. or interactive interpreter
else
  puts "Awesome REPL, CTRL+C to quit"
  loop do
    line = Readline::readline(">> ") # Read
    Readline::HISTORY.push(line)
    value = interpreter.eval(line) # Eval
    puts "=> #{value.ruby_value.inspect}" # Print
  end # Loop
end